# Write a python program to create a dictionary which contains student’s names and marks. Iterate over the dictionary and apply below conditions to print their grades


In [ ]:
students = dict() #This is a variable called students that is assigned to an empty dictionary.
n = int(input("Enter number of students :"))#This is a function that takes in an input from 
#the user and stores it as a variable. The function then converts the input into an integer.

for i in range(n):#This is a for loop that iterates through the range of n
        sname = input("Enter names of student :")#This is a function that allows the user to input their name.
        marks= []#This is a list. It stores the marks of each student.
        avg=0 #This is a variable that stores the sum of all the marks. It is initialized to 0.
        for j in range(5):#This is a for loop that iterates 5 times.
            mark = float(input("Enter marks :"))#This is a function that takes in user input and converts it to a float.
            marks.append(mark)#Answer: This is a function that adds an element to the end of the list. It takes one parameter, which is the element to be added. The syntax for this function is as follows:

#list_name.append(element) # where list_name is the name of the list and element is what you want to add to it.
            print(marks)   
            avg=avg+marks[j]
        
        avg1=avg/5
        print("Average marks is ",avg1)   
        if(avg1>=90.0):
            print("Grade: A")
        elif(avg1>=80.0 and avg1<90.0):
            print("Grade: B")
        elif(avg1>=70.0 and  avg1<80.0):
            print("Grade: C")
        elif(avg1>=60.0 and  avg1<70.0):
            print("Grade: D")
        else:
            print("Grade: F")
        students[sname] = marks
        print("Dictionary of student created :")
        print(students)

# # Write a Python Program to create a 1D array of numbers from 0 to 9. 


In [ ]:
#This code imports a library called numpy, which is used for scientific 
#computing. It then creates an array of numbers from 0 to 9 with a step size of 1. Finally, it prints the array.
import numpy as np   #This is a function that creates an array of numbers from 0 to 10.
nums = np.arange(0, 10,1)
print("One-dimensional array of single digit numbers:") 
print(nums)#This is a function that prints the array of numbers.

In [6]:
num1 = np.arange(100, 201)
print("\nOne-dimensional array of three digit numbers:") 
print(num1)


One-dimensional array of three digit numbers:
[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153
 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171
 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189
 190 191 192 193 194 195 196 197 198 199 200]


# Write a NumPy program to create an array of all the even integers  from 30 to 70. 

In [7]:
import numpy as np
array=np.arange(30,71,2)
print("Array of all the even integers from 30 to 70")
print(array)


Array of all the even integers from 30 to 70
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


# Write a NumPy program to create a 3x4 matrix filled with values  from 10 to 21.

In [8]:
import numpy as np
a = np.arange(10,22).reshape((4,3))
print("Original array:")
print(a)

Original array:
[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]]


# Write a NumPy program to compute the sum of all elements, sum of  each column and sum of each row of a given array.

In [9]:
import numpy as np
num = np.arange(40).reshape((8,5))
#arr1 = np.reshape(num, [8,5])
print("Original array:")
print(num)
#result  = arr1.sum(axis=0)
#print("\nSum of all columns:")
#print(result)


Original array:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]]


In [10]:
import numpy as np
num = np.arange(40)
arr1 = np.reshape(num, [8,5])
print("Original array:")
print(arr1)
result  = arr1.sum(axis=0)
print("\nSum of all rows:")
print(result)

Original array:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]]

Sum of all rows:
[140 148 156 164 172]


In [ ]:
import numpy as np
num = np.arange(40)
arr1 = np.reshape(num, [8,5])
print("Original array:")
print(arr1)
result  = arr1.sum()
print("\nSum of all elements:")
print(result)